# Generated by Django 3.0.5 on 2020-04-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_districts_regions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.RenameField(
            model_name='hepepsteam',
            old_name='Desc',
            new_name='Bio',
        ),
        migrations.RenameField(
            model_name='hepepsteam',
            old_name='Read_more',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='hepepsteam',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='hepepsteam',
            name='other_names',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hepepsteam',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hepepsteam',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
