# Generated by Django 3.0.5 on 2020-04-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200501_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hepepsteam',
            name='other_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hepepsteam',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
