# Generated by Django 3.0.5 on 2020-05-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200501_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
