# Generated by Django 3.0.5 on 2020-05-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backgroundimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimages',
            options={'verbose_name_plural': 'BackgroundImages'},
        ),
    ]
