# Generated by Django 3.0.5 on 2020-05-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200501_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimages',
            options={'verbose_name_plural': 'Background Images'},
        ),
        migrations.AlterModelOptions(
            name='hepepsteam',
            options={'verbose_name_plural': 'HepepsTeam'},
        ),
    ]
