# Generated by Django 3.0.5 on 2020-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200501_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_desc', models.TextField()),
                ('service_img', models.ImageField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='hepepsteam',
            options={'verbose_name_plural': 'Hepeps Team'},
        ),
    ]
